GET http://localhost:3000/users

###

POST http://localhost:3000/users/add
Content-Type: application/json

{
    "username": "yoda",
    "password": "yoda"
}

###

POST http://localhost:3000/users/login
Content-Type: application/json

{
    "username": "chili",
    "password": "katt"
}